name: Build and deploy to itch.io

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: fishing-prototype

jobs:
  buildAndTestForLinuxBasedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-24.04
    environment: PRODUCTION
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ./
        unityVersion:
          - 2022.3.12f1
        targetPlatform:
          - WebGL # Must be valid options for Unity: https://docs.unity3d.com/ScriptReference/BuildTarget.html
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Unity builds take some time, so we do some caching to make builds faster
      - name: Restore Unity Library cache
      - uses: actions/cache@v4
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ env.PROJECT_NAME }}-${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ env.PROJECT_NAME }}-${{ matrix.unityVersion }}-
            Library-${{ env.PROJECT_NAME }}-
            Library-
      # We use Game CI (https://game.ci/) to buld the project
      - name: Build Unity project
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: ${{ env.PROJECT_NAME }}
          buildsPath: build/${{ matrix.unityVersion }}/${{ matrix.targetPlatform }}
      # Install itch.io Butler
      - name: Setup Butler
        uses: remarkablegames/setup-butler@v3

      # Publish the WebGL build to itch.io
      - name: Publish to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
        run: |
          butler push \
            "build/${{ matrix.unityVersion }}/${{ matrix.targetPlatform }}" \
            "${{ vars.ITCH_USER }}/${{ vars.ITCH_GAME }}:html5"